is:
  - headers.acceptJson
  - headers.contentTypeJson
  - headers.testScenarioHeader
  - errors.formatNino
  - errors.formatTaxYear
  - errors.ruleTaxYearRangeInvalid
  - errors.ruleTaxYearNotSupported
  - errors.formatValue
  - errors.formatString
  - errors.ruleGiftAidNonUkAmountWithoutNames
  - errors.ruleNonUkGiftsAmountWithoutNames
  - errors.incorrectOrEmptyBody
  - errors.clientOrAgentNotAuthorised
  - errors.notFound
displayName: Create and Amend Charitable Giving Tax Relief [test only]
description: This endpoint allows a developer to create and amend charitable giving tax relief for a tax year. A National Insurance number, and tax year must be provided.
(annotations.sandboxData): !include ../scenarios/amend_charitable_givings.md
(annotations.scope): "write:self-assessment"
securedBy: [ sec.oauth_2_0: { scopes: [ "write:self-assessment" ] } ]
body:
  application/json:
    type: !include ../schemas/charitable_givings_payload.json
    examples:
      example-1:
        description: Charitable Giving Request
        value: !include ../examples/charitable_givings_payload.json
responses:
 200:
   body:
     application/json:
       type: !include ../schemas/charitable_givings_links.json
       examples:
         example-1:
           description: Charitable Giving Response
           value: !include ../examples/charitable_givings_links.json
   headers:
     X-CorrelationId:
       example: c75f40a6-a3df-4429-a697-471eeec46435
       description: Unique ID for operation tracking <br> String, 36 characters.

