is:
  - headers.acceptJson
  - headers.testScenarioHeader
  - errors.formatNino
  - errors.formatTaxYear
  - errors.ruleTaxYearRangeInvalid
  - errors.ruleTaxYearNotSupported
  - errors.clientOrAgentNotAuthorised
  - errors.notFound
displayName: Retrieve Pensions Reliefs
description: 'This endpoint allows the developer to retrieve tax relief on pension contributions. A National Insurance number and tax year must be provided.'
(annotations.sandboxData): !include ../scenarios/retrieve_relief_pensions.md
(annotations.scope): "read:self-assessment"
securedBy: [ sec.oauth_2_0: { scopes: [ "read:self-assessment" ] } ]
responses:
 200:
   body:
     application/json:
       type: !include ../schemas/retrieve_relief_pensions_response.json
       examples:
         example-1:
           description: Example response
           value: !include ../examples/retrieve_relief_pensions_response.json
   headers:
     X-CorrelationId:
       example: c75f40a6-a3df-4429-a697-471eeec46435
       description: Unique ID for operation tracking <br> String, 36 characters.