is:
  - headers.acceptJson
  - headers.contentTypeJson
  - headers.testScenarioHeader
  - errors.formatNino
  - errors.formatTaxYear
  - errors.ruleTaxYearRangeInvalid
  - errors.formatValue
  - errors.incorrectOrEmptyBody
  - errors.clientOrAgentNotAuthorised
  - errors.formatDateOfInvestment
  - errors.notFound
displayName: Amend Relief Investments [test only]
description: 'This endpoint allows a developer to amend relief investments from: VCT subscriptions, EIS subscriptions, Community Investments, Seed Enterprise Investments and Social Enterprise Investments. A National Insurance number and tax year must be provided.'
(annotations.sandboxData): !include scenarios/amend_relief_investments.md
(annotations.scope): "write:self-assessment"
securedBy: [ sec.oauth_2_0: { scopes: [ "write:self-assessment" ] } ]
body:
  application/json:
    type: !include schemas/amend_relief_investments_request.json
    examples:
      example-1:
        description: Default Example
        value: !include examples/amend_relief_investments_request.json
responses:
 200:
   body:
     application/json:
       type: !include schemas/amend_relief_investments_response.json
       examples:
         example-1:
           description: Example response
           value: !include examples/amend_relief_investments_response.json
   headers:
     X-CorrelationId:
       example: c75f40a6-a3df-4429-a697-471eeec46435
       description: Unique ID for operation tracking <br> String, 36 characters.